logging:
  group:
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  file:
    name: application.log
  level:
    root: WARN
    tomcat: INFO
    org:
      springframework: DEBUG
    com:
      example:
        learnmongo: DEBUG
---

spring:
  data:
    mongodb:
      database: application_db
